name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and restart app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ubuntu@13.60.47.33
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: |
            cd /home/ubuntu/my-app
            npm install
            npm run build
            npm run start
